from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('about_us', views.about_us, name='about_us'),
    path('blog_details', views.blog_details, name='blog_details'),
    path('blog_details_1', views.blog_details_1, name='blog_details_1'),
    path('cart', views.cart, name='cart'),
    path('category', views.category, name='category'),
    path('category_detail', views.category_detail, name='category_detail'),
    path('checkout', views.checkout, name='checkout'),
    path('coming_soon', views.coming_soon, name='coming_soon'),
    path('contact_us', views.contact_us, name='contact_us'),
    path('dashboard', views.dashboard, name='dashboard'),
    path('dashboard_addtour', views.dashboard_addtour, name='dashboard_addtour'),
    path('dashboard_booking', views.dashboard_booking, name='dashboard_booking'),
    path('dashboard_history', views.dashboard_history, name='dashboard_history'),
    path('dashboard_list', views.dashboard_list, name='dashboard_list'),
    path('dashboard_my_profile', views.dashboard_my_profile, name='dashboard_my_profile'),
    path('dashboard_reviews', views.dashboard_reviews, name='dashboard_reviews'),
    path('error', views.error, name='error'),
    path('faq', views.faq, name='faq'),
    path('forgot_password', views.forgot_password, name='forgot_password'),
    path('index_1', views.index_1, name='index_1'),
    path('index_2', views.index_2, name='index_2'),
    path('index_3', views.index_3, name='index_3'),
    path('index_4', views.index_4, name='index_4'),
    path('index_5', views.index_5, name='index_5'),
    path('index_6', views.index_6, name='index_6'),
    path('login', views.login, name='login'),
    path('mag', views.mag, name='mag'),
    path('mag_fashion', views.mag_fashion, name='mag_fashion'),
    path('mag_fitness', views.mag_fitness, name='mag_fitness'),
    path('mag_food', views.mag_food, name='mag_food'),
    path('mag_photo', views.mag_photo, name='mag_photo'),
    path('mag_sports', views.mag_sports, name='mag_sports'),
    path('mag_tech', views.mag_tech, name='mag_tech'),
    path('mag_travel', views.mag_travel, name='mag_travel'),
    path('shop', views.shop, name='shop'),
    path('post_details', views.post_details, name='post_details'),
    path('shop_detail', views.shop_detail, name='shop_detail'),
    path('tag', views.tag, name='tag'),
    path('tag_detail', views.tag_detail, name='tag_detail'),
    path('tag_details', views.tag_details, name='tag_details'),

]
